version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./src/main/java/com/example/csvuploader/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources:/app/resources