---
openapi: 3.0.0
info:
  title: CSVUploader API
  description: A backend application for managing and processing CSV data.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/csv/upload:
    post:
      summary: Upload a CSV file
      description: Uploads a CSV file and saves its contents into the database.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: The CSV file to upload.
                  example: data.csv
      responses:
        "200":
          description: CSV uploaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: CSV uploaded successfully.
        "400":
          description: Invalid file format or request error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid file format. Only CSV files are allowed.
        "500":
          description: Internal server error during file processing.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An unexpected error occurred while processing the file.
  /api/csv:
    get:
      summary: Retrieve all records
      description: Retrieves all stored CSV records from the database.
      responses:
        "200":
          description: A list of all records.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CsvRecord"
              example:
                - code: "271636001"
                  source: ZIB
                  codeListCode: ZIB001
                  displayValue: Polsslag regelmatig
                  longDescription: The long description is necessary.
                  fromDate: 2018-12-31T22:00:00.000+00:00
                  toDate: null
                  sortingPriority: 1
                - code: "61086009"
                  source: ZIB
                  codeListCode: ZIB001
                  displayValue: Polsslag onregelmatig
                  longDescription: ""
                  fromDate: 2018-12-31T22:00:00.000+00:00
                  toDate: null
                  sortingPriority: 2
        "204":
          description: No records found.
        "500":
          description: Internal server error.
    delete:
      summary: Delete all records
      description: Deletes all records from the database.
      responses:
        "200":
          description: All records were successfully deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: All records deleted successfully.
        "500":
          description: Internal server error during deletion.
  "/api/csv/{code}":
    get:
      summary: Retrieve a record by code
      description: Retrieves a specific record using its unique code.
      parameters:
        - name: code
          in: path
          required: true
          description: The unique code of the record.
          schema:
            type: string
            example: "271636001"
      responses:
        "200":
          description: The record matching the provided code.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CsvRecord"
              example:
                code: "271636001"
                source: ZIB
                codeListCode: ZIB001
                displayValue: Polsslag regelmatig
                longDescription: The long description is necessary.
                fromDate: 2018-12-31T22:00:00.000+00:00
                toDate: null
                sortingPriority: 1
        "404":
          description: Record not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Record with code '271636001' not found.
        "500":
          description: Internal server error.
components:
  schemas:
    CsvRecord:
      type: object
      properties:
        code:
          type: string
          description: Unique code for the record.
          example: "271636001"
        source:
          type: string
          description: Source of the data.
          example: ZIB
        codeListCode:
          type: string
          description: Reference to the code list.
          example: ZIB001
        displayValue:
          type: string
          description: Display value of the record.
          example: Polsslag regelmatig
        longDescription:
          type: string
          description: Detailed description of the record.
          example: The long description is necessary.
        fromDate:
          type: string
          format: date-time
          description: Start date of the record.
          example: 2018-12-31T22:00:00.000+00:00
        toDate:
          type: string
          format: date-time
          description: End date of the record (nullable).
          example: null
        sortingPriority:
          type: number
          description: Sorting priority of the record.
          example: 1
